/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cs394_jas38_pdultrasonicclassification_Broker */

#ifndef _Included_com_cs394_jas38_pdultrasonicclassification_Broker
#define _Included_com_cs394_jas38_pdultrasonicclassification_Broker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cs394_jas38_pdultrasonicclassification_Broker
 * Method:    callNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_cs394_jas38_pdultrasonicclassification_Broker_callNative
  (JNIEnv *, jobject);

/*
 * Class:     com_cs394_jas38_pdultrasonicclassification_Broker
 * Method:    callIntNative
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_cs394_jas38_pdultrasonicclassification_Broker_callIntNative
  (JNIEnv *, jobject);

/*
 * Class:     com_cs394_jas38_pdultrasonicclassification_Broker
 * Method:    CallNativeOpenFile
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jdoubleArray JNICALL Java_com_cs394_jas38_pdultrasonicclassification_Broker_CallNativeOpenFile
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
